### ISSUE TITLE
Find encryption keys is not working

### ISSUE THREAD

**Issue by mquandalle** [jparyani/Mailpile#4]
Neither the “search for a key” or “upload a key” seems to be working on the new port of Mailpile for sandstorm.

**Comment by ocdtrekkie** [comment]
I believe it's a known thing that crypto is not yet working in the Mailpile port and never has? Did that work in the old version?

**Comment by jparyani** [comment]
ocdtrekkie is correct, we've purposely removed a lot of the GPG functionality from Mailpile's Sandstorm port. The reasoning behind this is that Mailpile assumes its encryption keys are local, and it defeats much of the purpose to have your GPG key hosted in a remote Sandstorm grain.

Looking forward, once we have GPG login or maybe even just GPG as a capability exposed through the Powerbox, we should be able to rewire Mailpile to use it instead.

Thanks for reporting about the buttons not working. I'll remove them until they become useful again :)

**Comment by jparyani** [comment]
Fixed in 731b8f03841c5bb0f259d2a47badba7a677a01a8
