### ISSUE TITLE
Find Encryption Keys feature is broken, how to upload keys?

### ISSUE THREAD

**Issue by JamborJan** [jparyani/Mailpile#6]
How can I upload encryption keys to Mailpile? The "Find Encryption Keys" feature seems to be not working as shown on the following pictures.

Tested with Sandstorm 0.68 and Mailpile version Feb 6 2015.

![find_key_01](https://cloud.githubusercontent.com/assets/7508960/6864478/f882a694-d461-11e4-9486-ba03cd976ed7.png)
![find_key_02](https://cloud.githubusercontent.com/assets/7508960/6864480/f8a9e93e-d461-11e4-8a59-9d9d1c6d71aa.png)
![find_key_03](https://cloud.githubusercontent.com/assets/7508960/6864479/f8a7b2ae-d461-11e4-9704-2f08d28cf981.png)

**Comment by jparyani** [comment]
So as I said in #5, we disabled the GPG functionality in Mailpile. I must've missed some parts of the UI that have changed to using it, so I'll have to go through and fix them all.

Eventually, we do want to add back in GPG support, but it's probably going to be a while until we figure out a good way to do it securely.
